export const TEXTS = {
  AMOR: "Amor, known as Cupid in Roman mythology and Eros in Greek mythology, is the god of love and desire. Often depicted as a playful, winged child carrying a bow and arrows, he wields the power to ignite passion and affection by striking the hearts of gods and mortals alike. In myths, Amor is both mischievous and deeply symbolic, representing the unpredictable and transformative nature of love. While he sometimes acts impulsively, his role in the story of Amor und Psyche reveals his depth, as he defies his mother Venus's will to protect and unite with Psyche, showing that even love's god can experience vulnerability and devotion.",
  STORY_1: `The sculpture of Amor und Psyche immortalizes the tender moment when the god of love, Amor, awakens the mortal Psyche from her enchanted slumber. Psyche, her beauty otherworldly yet fragile, reclines with a soft grace, her delicate limbs resting as if still caught between the dream and the waking world. Amor kneels beside her, his strong yet gentle form leaning in to rouse her. His wings, intricately detailed, arc behind him, suggesting both his divinity and the swiftness with which he descended to her. The subtle tilt of his head and the light touch of his hand on her face convey an intimate mix of devotion and relief, encapsulating the moment when love triumphs over trials and separation.`,
  STORY_2: `As Psyche begins to awaken, her body stirs, her hands rising instinctively toward Amor in a gesture of trust and recognition. The sculpture conveys not only the physical reunion of the lovers but also the spiritual union of love (Amor) and the soul (Psyche), a bond forged through suffering, perseverance, and divine grace. The interplay of light and shadow across the flowing drapery and the softness of their expressions evoke a sense of transcendence, as though the sculpture itself breathes with life. In this eternal moment, Amor and Psyche are no longer separated by mortality or divine will, embodying the ultimate harmony of love’s redemptive power and the soul’s yearning for unity.`,
  PSYCHE: `Psyche, whose name means "soul" in Greek, is a mortal woman of extraordinary beauty who becomes the central figure in the myth of Amor und Psyche. Her beauty draws the envy of Venus and leads to a series of divine trials that test her courage, determination, and faith. Despite her initial naivety, Psyche's journey symbolizes the soul’s growth and transformation through challenges. Her enduring love for Amor and her willingness to face hardships for their union reflect the profound connection between love and the human spirit. Psyche ultimately achieves immortality, signifying the eternal nature of true love and the soul's ascension.`,
};
export const HerculesTexts = {
  HERCULES: `Hercules, known as Heracles in Greek mythology, is a demigod celebrated for his extraordinary strength and heroic deeds. The son of Zeus and the mortal Alcmene, he is famed for his Twelve Labors, which include slaying the Nemean Lion and capturing the Erymanthian Boar. Despite his immense power, Hercules' life was fraught with challenges, including conflicts with the goddess Hera and personal tragedies. Ultimately, he achieved immortality and ascended to Olympus, embodying resilience and the human quest for redemption.`,

  ARCHELOUS: `Achelous, the ancient Greek river god, symbolizes the untamed forces of water and nature. Known for his ability to shapeshift, he often took on the form of a bull or serpent in mythology. One of his most famous tales involves his battle with Hercules for the hand of Deianira. Despite his transformations, Achelous was defeated when Hercules broke off one of his horns, which was later turned into the cornucopia, a symbol of abundance and prosperity.`,

  STORY_1: `Hercules, the demigod famed for his strength and valor, stood by the banks of the river Achelous, preparing to face the river god Archelous for the hand of the beautiful Deianira. Archelous, determined to prove his superiority, mocked Hercules, claiming that his divine powers far outweighed the hero's brute strength. In his arrogance, the river god transformed himself into a colossal serpent, his shimmering scales reflecting the sunlight as his body coiled menacingly around the hero. Hercules, undaunted by the transformation, gripped his mighty club tightly and prepared to confront this new form of his foe.`,
  STORY_2: `Archelous, in his serpentine form, lunged at Hercules with lightning speed, fangs bared to strike. The demigod leaped aside, dodging the venomous bite, and countered with a powerful blow of his club. The clash shook the ground as the serpent lashed out with its massive tail, attempting to ensnare Hercules in its coils. The hero, using his legendary strength, wrestled with the serpent, his hands gripping its slippery scales as he evaded its crushing grip. Despite its immense size and speed, the serpent could not match Hercules' determination, and soon its once-confident strikes grew sluggish and desperate.`,
  STORY_3: `Summoning all his strength, Hercules seized the serpent by its neck, squeezing with an iron grip that no mortal could withstand. The river god writhed and thrashed, but even in his divine form, he was no match for the son of Zeus. With a final, earth-shaking effort, Hercules hurled the defeated serpent to the ground. Archelous, humbled and exhausted, reverted to his true form and conceded defeat, granting Hercules the right to wed Deianira. The hero stood triumphant by the river's edge, a testament to the power of courage and determination against even the mightiest of adversaries.`,
};
